# DO NOT EDIT THIS FILE!
#
# This file is generated from the CDP specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# CDP domain: DigitalCredentials (experimental)

from __future__ import annotations
import enum
import typing
from dataclasses import dataclass
from .util import event_class, T_JSON_DICT

from . import page


class VirtualWalletAction(enum.Enum):
    '''
    The type of virtual wallet action.
    '''
    RESPOND = "respond"
    DECLINE = "decline"
    WAIT = "wait"
    CLEAR = "clear"

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> VirtualWalletAction:
        return cls(json)


def set_virtual_wallet_behavior(
        action: VirtualWalletAction,
        protocol: typing.Optional[str] = None,
        response: typing.Optional[dict] = None,
        frame_id: typing.Optional[page.FrameId] = None
    ) -> typing.Generator[T_JSON_DICT,T_JSON_DICT,None]:
    '''
    Sets the behavior of the virtual wallet for digital credential requests
    issued from this frame.

    :param action: The action of the virtual wallet.
    :param protocol: *(Optional)* The protocol identifier (e.g. "openid4vp"). Required when ``action`` is "respond", forbidden otherwise.
    :param response: *(Optional)* The response data object returned by the wallet. Required when ``action`` is "respond", forbidden otherwise.
    :param frame_id: *(Optional)* The frame to scope the virtual wallet behavior to.
    '''
    params: T_JSON_DICT = dict()
    params['action'] = action.to_json()
    if protocol is not None:
        params['protocol'] = protocol
    if response is not None:
        params['response'] = response
    if frame_id is not None:
        params['frameId'] = frame_id.to_json()
    cmd_dict: T_JSON_DICT = {
        'method': 'DigitalCredentials.setVirtualWalletBehavior',
        'params': params,
    }
    json = yield cmd_dict
