# DO NOT EDIT THIS FILE!
#
# This file is generated from the CDP specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# CDP domain: FindInPage (experimental)

from __future__ import annotations
import enum
import typing
from dataclasses import dataclass
from .util import event_class, T_JSON_DICT


def find_first(
        query: str
    ) -> typing.Generator[T_JSON_DICT,T_JSON_DICT,None]:
    '''
    Forwards ``query`` to the find-in-page facility, starting a new find session.
    Where exactly the search starts from is implementation-specific.

    :param query:
    '''
    params: T_JSON_DICT = dict()
    params['query'] = query
    cmd_dict: T_JSON_DICT = {
        'method': 'FindInPage.findFirst',
        'params': params,
    }
    json = yield cmd_dict


def find_next() -> typing.Generator[T_JSON_DICT,T_JSON_DICT,None]:
    '''
    Moves to the next match for the query passed to the most recent
    findFirst() call.
    '''
    cmd_dict: T_JSON_DICT = {
        'method': 'FindInPage.findNext',
    }
    json = yield cmd_dict


def find_prev() -> typing.Generator[T_JSON_DICT,T_JSON_DICT,None]:
    '''
    Moves to the previous match for the query passed to the most recent
    findFirst() call.
    '''
    cmd_dict: T_JSON_DICT = {
        'method': 'FindInPage.findPrev',
    }
    json = yield cmd_dict


def stop() -> typing.Generator[T_JSON_DICT,T_JSON_DICT,None]:
    '''
    Ends the current find session, if any, and clears its highlighting.
    '''
    cmd_dict: T_JSON_DICT = {
        'method': 'FindInPage.stop',
    }
    json = yield cmd_dict
